routes/web.php
<?php

use App\Http\Controllers\ContactController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DatabaseController;
use App\Http\Controllers\EducationalLevelController;
use App\Http\Controllers\EducationRecordController;
use App\Http\Controllers\FrameworkController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\LibraryController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\ReligionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\SocialMediaController;
use App\Http\Controllers\ToolController;
use App\Http\Controllers\WorkExperienceController;
use App\Http\Controllers\WorkTypeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard.index');
    Route::group(['prefix' => 'setting','as' => 'setting.'], function () {
        Route::resource('database',DatabaseController::class);
        Route::resource('tool',ToolController::class);
        Route::resource('language',LanguageController::class);
        Route::resource('framework',FrameworkController::class);
        Route::resource('religion',ReligionController::class);
        Route::resource('social-media',SocialMediaController::class);
        Route::resource('work-type',WorkTypeController::class);
        Route::resource('service',ServiceController::class);
        Route::resource('library',LibraryController::class);
        Route::resource('role',RoleController::class);
        Route::resource('educational-level',EducationalLevelController::class);
    });
    Route::resource('profile',ProfileController::class);
    Route::resource('education-record',EducationRecordController::class);
    Route::resource('work-experience',WorkExperienceController::class);
    Route::resource('contact',ContactController::class);
    Route::resource('project',ProjectController::class);
});
Route::post('image/store',[ImageController::class,'store'])->name('image.store');
Route::get('/', function () {
    return view('client.home');
})->name('client.home');
Route::get('/work', function () {
    return view('client.work-show');
})->name('work.show');

resources/views/contact.blade.php
@extends('layouts.admin.app')

@push('css')
    <link rel="stylesheet" type="text/css" href="{{ asset('custom/css/datatables.min.css') }}"/>
    <link rel="stylesheet" href="{{ asset('custom/css/my.css') }}">
@endpush
@section('breadcrumb')
    <div class="page-header">
        <h3 class="page-title"> Contact </h3>
        <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">Contact</li>
        </ol>
        </nav>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
            <p class="card-description">
                <button type="button" class="btn btn-inverse-primary" data-toggle="modal" data-target="#modal_add"><i class="mdi mdi-plus"></i>Tambah</button>
            </p>
            <div class="template-demo">
                <x-table id="datatable">
                    @slot('head')
                        <tr>
                            <th>No.</th>
                            <th>Foto</th>
                            <th>Nama</th>
                            <th>Tipe</th>
                            <th>Badan Hukum</th>
                            <th>Aksi</th>
                        </tr>
                    @endslot
                </x-table>
            </div>
            </div>
        </div>
        </div>
    </div>
@endsection

@section('modal')
    <x-modal id="modal_add" header="Form Tambah" size="lg">
        <x-form action="" method="post" submit="Simpan" id="form_add">
            <div class="row">
                <div class="col">
                    <x-input id="add_name" name="add_name" label="Nama" placeholder="Cth. Lio"/>
                    <x-textarea id="add_address" name="add_address" label="Alamat" placeholder="Cth. Jalan Rungkut Mejoyo Selatan"/>
                    <x-checkbox id="add_is_developer" name="add_is_developer" label="Pengembang"/>
                    <x-select id="add_legal_entity" name="add_legal_entity" label="Badan Hukum" :options="$legal_entities"/>
                </div>
                <div class="col">
                    <x-select id="add_social_medias" name="add_social_medias" label="Sosial Media" :options="$sosmeds" multiple="multiple"/>
                    <x-table id="sosmed-table">
                        @slot('head')
                            <tr>
                                <th>Nama</th>
                                <th>Akun</th>
                                <th>Link</th>
                            </tr>
                        @endslot
                        @slot('body')
                        @endslot
                    </x-table>
                </div>
            </div>

        </x-form>
    </x-modal>
    <x-modal id="modal_edit" header="Form Edit" size="lg">
        <x-form action="" method="put" submit="Update" id="form_edit">
            <div class="row">
                <div class="col">
                    <x-input id="edit_name" name="edit_name" label="Nama" placeholder="Cth. Lio"/>
                    <x-textarea id="edit_address" name="edit_address" label="Alamat" placeholder="Cth. Jalan Rungkut Mejoyo Selatan"/>
                    <x-checkbox id="edit_is_developer" name="edit_is_developer" label="Pengembang"/>
                    <x-select id="edit_legal_entity" name="edit_legal_entity" label="Badan Hukum" :options="$legal_entities"/>
                </div>
                <div class="col">
                    <x-select id="edit_social_medias" name="edit_social_medias" label="Sosial Media" :options="$sosmeds" multiple="multiple"/>
                    <x-table id="edit-sosmed-table">
                        @slot('head')
                            <tr>
                                <th>Nama</th>
                                <th>Akun</th>
                                <th>Link</th>
                            </tr>
                        @endslot
                        @slot('body')
                        @endslot
                    </x-table>
                </div>
            </div>
        </x-form>
    </x-modal>
@endsection

@push('js')
    <script type="text/javascript" src="{{ asset('custom/js/datatables.min.js') }}"></script>
    <script>
        let index_url = "{{ route('contact.index') }}"
        let store_url = "{{ route('contact.store') }}"
        let update_url = "{{ route('contact.update','-id-') }}"
        let delete_url = "{{ route('contact.destroy','-id-') }}"
        let using_ajax_get_request = 1
        $('.select-multiple').select2();

        var sosmed_name = @json($sosmeds);
        var sosmed_selected = []

        $('#add_social_medias,#edit_social_medias').on('select2:select', function (e) {
            $(this).val().forEach(e => {
              if(!sosmed_selected.find( x => x.id == e)){
                sosmed_selected.push({ id : e,name:sosmed_name[e] ?? '-', akun : '', link : '' })
              }
            });
            let action = 1
            if(e.currentTarget.id == 'edit_social_medias'){
                action = 2
            }
            draw_on_table(sosmed_selected,action)
        });

        $('#add_social_medias,#edit_social_medias').on('select2:unselecting', function (e) {
            let unselected_id = e.params.args.data.id
            sosmed_selected = sosmed_selected.filter(function(e, index, arr){
                return e.id != unselected_id;
            });
            let action = 1
            if(e.currentTarget.id == 'edit_social_medias'){
                action = 2
            }
            draw_on_table(sosmed_selected,action)
        });

        function changeInfo(info,id){
            if(info==1){
                sosmed_selected.find( x => x.id == id).akun = $('#akun_'+id).val()
            }else if(info==2){
                sosmed_selected.find( x => x.id == id).link = $('#link_'+id).val()
            }
        }

        function draw_on_table(params,action = 1){ // action: 1, create|2, update
            let html = ''
            params.forEach(e => {
                let akun_id = (action == 1 ? 'akun_' : 'edit_akun_') + e.id
                let link_id = (action == 1 ? 'link_' : 'edit_link_') + e.id
                let akun_name = action == 1 ? 'akun[]' : 'edit_akun[]'
                let link_name = action == 1 ? 'link[]' : 'edit_link[]'
                let main_id = action == 1 ? 'sosmeds[]' : 'edit_sosmeds[]'
                html+='<input type=\"hidden\" name="'+main_id+'" value=\"'+e.id+'\" ></td>'
                html+='<tr><td>'+e.name+'</td><td><input id="'+akun_id+'" name="'+akun_name+'" type=\"text\" class=\"form-control\" value=\"'+e.akun+'\" placeholder=\"Akun...\" onChange="changeInfo(1,'+e.id+')"></td>'
                html+='<td><input type=\"text\" id="'+link_id+'" name="'+link_name+'" class=\"form-control\" value=\"'+e.link+'\" placeholder=\"Link...\" onChange="changeInfo(2,'+e.id+')"></td></tr>'
            });
            if(action == 1){
                $('#sosmed-table tbody').html(html)
            }else{
                $('#edit-sosmed-table tbody').html(html)
            }
        }

        let columns = [
            { data: 'photo', searchable: false, orderable: false },
            { data: 'name' },
            { data: 'is_developer' },
            { data: 'legal_entity' },
        ]
        function show_detail(data) {
            $('#edit_name').val(data.name)
            $('#edit_address').val(data.address)
            $("#edit_is_developer").prop("checked", data.is_developer);
            $('#edit_legal_entity').val(data.legal_entity)
            let temp = []
            sosmed_selected = []
            data.sosmed.forEach(e => {
                temp.push(e.id)
                sosmed_selected.push({ id : e.id,name:sosmed_name[e.id] ?? '-', akun : e.account, link : e.link })
            });
            $('#edit_social_medias').val(temp).trigger('change');
            draw_on_table(sosmed_selected,2)
        }

        let table = generate_datatable('Contact',index_url,columns)
        generate_update_listener('form_edit',table)
        generate_store_listener('form_add',store_url,table)
        generate_delete_listener(delete_url,table)
        generate_show_listener(update_url,using_ajax_get_request)
    </script>
@endpush

resources/views/education-record.blade.php
@extends('layouts.admin.app')

@push('css')
    <link rel="stylesheet" type="text/css" href="{{ asset('custom/css/datatables.min.css') }}"/>
    <link rel="stylesheet" href="{{ asset('custom/css/my.css') }}">
    <link rel="stylesheet" href="{{ asset('custom/css/bootstrap-datetimepicker.min.css') }}">
@endpush
@section('breadcrumb')
    <div class="page-header">
        <h3 class="page-title"> Education Record </h3>
        <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">Education Record</li>
        </ol>
        </nav>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
            <p class="card-description">
                <button type="button" class="btn btn-inverse-primary" data-toggle="modal" data-target="#modal_add"><i class="mdi mdi-plus"></i>Tambah</button>
            </p>
            <div class="template-demo">
                <x-table id="datatable">
                    @slot('head')
                        <tr>
                            <th>No.</th>
                            <th>Institusi</th>
                            <th>Masuk</th>
                            <th>Selesai</th>
                            <th>Aksi</th>
                        </tr>
                    @endslot
                </x-table>
            </div>
            </div>
        </div>
        </div>
    </div>
@endsection

@section('modal')
    <x-modal id="modal_add" header="Form Tambah">
        <x-form action="" method="post" submit="Simpan" id="form_add">
            <x-input id="add_institution_name" name="add_institution_name" label="Nama Institusi" placeholder="Universitas Surabaya"/>
            <x-select id="add_educational_level_id" name="add_educational_level_id" label="Tingkat" :options="$educational_levels"/>
            <x-input id="add_start_at" name="add_start_at" type="date" label="Masuk" placeholder="Tanggal Masuk"/>
            <x-input id="add_end_at" name="add_end_at" type="date" label="Masuk" placeholder="Tanggal Selesai"/>
            <x-textarea id="add_desc" name="add_desc" label="Deskripsi" placeholder="Lulus dengan gelar S.Kom"/>
        </x-form>
    </x-modal>
    <x-modal id="modal_edit" header="Form Edit">
        <x-form action="" method="put" submit="Update" id="form_edit">
            <x-input id="edit_institution_name" name="edit_institution_name" label="Nama Institusi" placeholder="Universitas Surabaya"/>
            <x-select id="edit_educational_level_id" name="edit_educational_level_id" label="Tingkat" :options="$educational_levels"/>
            <x-input id="edit_start_at" name="edit_start_at" type="date" label="Masuk" placeholder="Tanggal Masuk"/>
            <x-input id="edit_end_at" name="edit_end_at" type="date" label="Masuk" placeholder="Tanggal Selesai"/>
            <x-textarea id="edit_desc" name="edit_desc" label="Deskripsi" placeholder="Lulus dengan gelar S.Kom"/>
        </x-form>
    </x-modal>
@endsection

@push('js')
    <script type="text/javascript" src="{{ asset('custom/js/datatables.min.js') }}"></script>
    <script src="{{ asset('custom/js/moment.js') }}"></script>
    <script src="{{ asset('custom/js/id.js') }}"></script>
    <script type="text/javascript" src="{{ asset('custom/js/bootstrap-datetimepicker.min.js') }}"></script>


    <script>
        let index_url = "{{ route('education-record.index') }}"
        let store_url = "{{ route('education-record.store') }}"
        let update_url = "{{ route('education-record.update','-id-') }}"
        let delete_url = "{{ route('education-record.destroy','-id-') }}"
        let using_ajax_get_request = 1

        let columns = [
            { data: 'institution_name' },
            { data: 'start_at',searchable: false },
            { data: 'end_at',searchable: false }
        ]
        function show_detail(data) {
            $('#edit_name').val(data.name)
            $('#edit_institution_name').val(data.institution_name)
            $('#edit_educational_level_id').val(data.educational_level_id)
            $('#edit_start_at').val(data.start_at)
            $('#edit_end_at').val(data.end_at)
            $('#edit_desc').val(data.desc)
        }
        generate_datetimepicker('.datepicker','MMMM YYYY')

        let table = generate_datatable('Education Record',index_url,columns,[2, 'desc'])
        generate_update_listener('form_edit',table)
        generate_store_listener('form_add',store_url,table)
        generate_delete_listener(delete_url,table)
        generate_show_listener(update_url,using_ajax_get_request)
    </script>
@endpush

resources/views/project.blade.php
@extends('layouts.admin.app')

@push('css')
    <link rel="stylesheet" type="text/css" href="{{ asset('custom/css/datatables.min.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ asset('custom/css/my.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('custom/css/bootstrap-datetimepicker.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('custom/css/dropzone.min.css') }}">
@endpush

@section('breadcrumb')
    <div class="page-header">
        <h3 class="page-title"> Project </h3>
        <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">Project</li>
        </ol>
        </nav>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
            <p class="card-description">
                <button type="button" class="btn btn-inverse-primary" data-toggle="modal" data-target="#modal_add" onClick="reset()"><i class="mdi mdi-plus"></i>Tambah</button>
            </p>
            <div class="template-demo">
                <x-table id="datatable">
                    @slot('head')
                        <tr>
                            <th>No.</th>
                            <th>Nama</th>
                            <th>Peruntukan</th>
                            <th>Sifat</th>
                            <th>Mulai</th>
                            <th>Selesai</th>
                            <th>Aksi</th>
                        </tr>
                    @endslot
                </x-table>
            </div>
            </div>
        </div>
        </div>
    </div>
@endsection

@section('modal')
    <x-modal id="modal_add" header="Form Tambah" size="lg">
        <x-form action="" method="post" submit="Simpan" id="form_add">
            <div class="row">
                <div class="col dropzone m-3" id="add-dropzone">
                </div>
                <div class="col">
                    <x-input id="add_name" name="add_name" label="Nama" placeholder="Manajemen Rantai Pasok"/>
                    <div class="row">
                        <div class="col">
                            <x-checkbox id="add_is_commercial" name="add_is_commercial" label="Komersial"/>
                        </div>
                        <div class="col">
                            <x-checkbox id="add_is_new" name="add_is_new" label="Sistem Baru"/>
                        </div>
                    </div>
                    <x-select id="add_database_id" name="add_database_id" label="Basis Data" :options="$databases"/>
                    <x-input id="add_start_at" name="add_start_at" type="date" label="Mulai" placeholder="Tanggal Masuk"/>
                    <x-input id="add_end_at" name="add_end_at" type="date" label="Selesai" placeholder="Tanggal Selesai"/>
                    <x-textarea id="add_desc" name="add_desc" label="Deskripsi" rows="9" placeholder="Adalah sistem yang dibuat untuk menangani rantai pasok"/>
                </div>
                <div class="col">
                    <x-select id="add_framework_id" name="add_frameworks[]" label="Framework" :options="$frameworks" multiple="multiple"/>
                    <x-select id="add_library_id" name="add_libraries[]" label="Library" :options="$libraries" multiple="multiple"/>
                    <x-select id="add_participans" name="add_participans" label="Partisipan" :options="$contacts" multiple="multiple"/>
                    <x-table id="participan-table">
                        @slot('head')
                            <tr>
                                <th>Nama</th>
                                <th>Peran</th>
                            </tr>
                        @endslot
                        @slot('body')
                        @endslot
                    </x-table>
                </div>
            </div>
        </x-form>
    </x-modal>
    <x-modal id="modal_edit" header="Form Edit" size="lg">
        <x-form action="" method="put" submit="Update" id="form_edit">
            <div class="row">
                <div class="col dropzone m-3" id="edit-dropzone">
                </div>
                <div class="col">
                    <x-input id="edit_name" name="edit_name" label="Nama" placeholder="Manajemen Rantai Pasok"/>
                    <div class="row">
                        <div class="col">
                            <x-checkbox id="edit_is_commercial" name="edit_is_commercial" label="Komersial"/>
                        </div>
                        <div class="col">
                            <x-checkbox id="edit_is_new" name="edit_is_new" label="Sistem Baru"/>
                        </div>
                    </div>
                    <x-select id="edit_database_id" name="edit_database_id" label="Basis Data" :options="$databases"/>
                    <x-input id="edit_start_at" name="edit_start_at" type="date" label="Mulai" placeholder="Tanggal Masuk"/>
                    <x-input id="edit_end_at" name="edit_end_at" type="date" label="Selesai" placeholder="Tanggal Selesai"/>
                    <x-textarea id="edit_desc" name="edit_desc" label="Deskripsi" rows="9" placeholder="Adalah sistem yang dibuat untuk menangani rantai pasok"/>
                </div>
                <div class="col">
                    <div class="col">
                        <x-select id="edit_framework_id" name="edit_frameworks[]" label="Framework" :options="$frameworks" multiple="multiple"/>
                        <x-select id="edit_library_id" name="edit_libraries[]" label="Library" :options="$libraries" multiple="multiple"/>
                        <x-select id="edit_participans" name="edit_participans" label="Partisipan" :options="$contacts" multiple="multiple"/>
                        <x-table id="edit-participan-table">
                            @slot('head')
                                <tr>
                                    <th>Nama</th>
                                    <th>Peran</th>
                                </tr>
                            @endslot
                            @slot('body')
                            @endslot
                        </x-table>
                    </div>
                </div>
            </div>
        </x-form>
    </x-modal>
@endsection

@push('js')
    <script type="text/javascript" src="{{ asset('custom/js/datatables.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('custom/js/moment.js') }}"></script>
    <script type="text/javascript" src="{{ asset('custom/js/id.js') }}"></script>
    <script type="text/javascript" src="{{ asset('custom/js/bootstrap-datetimepicker.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('custom/js/dropzone.min.js') }}"></script>
    <script>
        Dropzone.autoDiscover = false;
        let dz_url = '{{ route('image.store') }}'
        let dz_token = '{{ csrf_token() }}'
        let addDz = generate_dropzone('add-dropzone','form_add',dz_url,dz_token)
        let editDz = generate_dropzone('edit-dropzone','form_edit',dz_url,dz_token)

        var participans = []
        var contacts = @json($contacts);
        let select = @json($select);

        function reset(){
            participans = []
            //add
            $('#add_participans').val([]).trigger('change');
            $('#participan-table tbody').html('')
            //edit
            $('#edit_participans').val([]).trigger('change');
            $('#edit-participan-table tbody').html('')
        }

        function change_value(id,select){
            participans.find( x => x.id == id).role = $('#'+select).val()
        }

        function draw_on_table(params,action = 1){ // action: 1, create|2, update
            let html = ''
            let list_selector = []
            params.forEach(e => {
                let selector = action == 1 ? 'role'+e.id : 'edit_role'+e.id
                html+='<input type=\"hidden\" name="participans[]" value=\"'+e.id+'\" ></td>'
                html+="<tr>"
                html+="<td>"+e.name+"</td>"
                html+="<td id='td_"+selector+"'>"+select.html+"</td>"
                html+="</tr>"
                list_selector.push({ id : e.id,selector : selector, role : e.role ?? null })
            });
            if(action == 1){
                $('#participan-table tbody').html(html)
            }else{
                $('#edit-participan-table tbody').html(html)
            }
            change_attr_select(list_selector)
        }

        function change_attr_select(list_selector){
            if(list_selector.length > 0){
                list_selector.forEach(e => {
                    $('#td_'+e.selector+' select').attr('id','select_'+e.selector)
                    let select_id = '#select_'+e.selector
                    $(select_id).val(e.role)
                    $(select_id).attr('onChange', "change_value('"+e.id+"','select_"+e.selector+"')");
                });
            }
        }

        function show_detail(data) {
            reset()
            $('#edit_name').val(data.name)
            $('#edit_database_id').val(data.database_id)
            $("#edit_is_commercial").prop("checked", data.is_commercial);
            $("#edit_is_new").prop("checked", data.is_new);
            $('#edit_start_at').val(data.start_at)
            $('#edit_end_at').val(data.end_at)
            $('#edit_desc').val(data.desc)
            let temp_framework = []
            let temp_library = []
            let temp_participan = []

            data.frameworks.forEach(e => {
                temp_framework.push(e.id)
            });
            data.libraries.forEach(e => {
                temp_library.push(e.id)
            });
            if(data.participans){
                data.participans.forEach(e => {
                    temp_participan.push(e.contact.id)
                    participans.push({ id : e.contact.id,name:e.contact.name ?? '-', role : e.role.id })
                });
            }
            draw_on_table(participans,2)
            $('#edit_framework_id').val(temp_framework).trigger('change');
            $('#edit_library_id').val(temp_library).trigger('change');
            $('#edit_participans').val(temp_participan).trigger('change');
            set_dropzone_preview(editDz,data.images,"{{ asset('images/project') }}",'form_edit')
        }

        $('#add_participans,#edit_participans').on('select2:select', function (e) {
            $(this).val().forEach(e => {
            if(!participans.find( x => x.id == e)){
                participans.push({ id : e,name:contacts[e] ?? '-', role : '' })
            }
            });
            let action = 1
            if(e.currentTarget.id == 'edit_participans'){
                action = 2
            }
            draw_on_table(participans,action)
        });

        $('#add_participans,#edit_participans').on('select2:unselecting', function (e) {
            let unselected_id = e.params.args.data.id
            participans = participans.filter(function(e, index, arr){
                return e.id != unselected_id;
            });
            let action = 1
            if(e.currentTarget.id == 'edit_participans'){
                action = 2
            }
            draw_on_table(participans,action)
        });

        $(document).ready(function(){
            let index_url = "{{ route('project.index') }}"
            let store_url = "{{ route('project.store') }}"
            let update_url = "{{ route('project.update','-id-') }}"
            let delete_url = "{{ route('project.destroy','-id-') }}"
            let using_ajax_get_request = 1
            $('.select-multiple').select2();

            generate_datetimepicker('.datepicker','DD MMMM YYYY')
            let columns = [
                { data: 'name' },
                { data: 'is_commercial',searchable: false},
                { data: 'is_new',searchable: false},
                { data: 'start_at',searchable: false },
                { data: 'end_at',searchable: false }
            ]
            let table = generate_datatable('Project',index_url,columns,[2, 'desc'])
            generate_update_listener('form_edit',table)
            generate_store_listener('form_add',store_url,table)
            generate_delete_listener(delete_url,table)
            generate_show_listener(update_url,using_ajax_get_request)
        })
    </script>
@endpush