routes/web.php
<?php

use App\Http\Controllers\ContactController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DatabaseController;
use App\Http\Controllers\EducationalLevelController;
use App\Http\Controllers\EducationRecordController;
use App\Http\Controllers\FrameworkController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\LibraryController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\ReligionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\SocialMediaController;
use App\Http\Controllers\ToolController;
use App\Http\Controllers\WorkExperienceController;
use App\Http\Controllers\WorkTypeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard.index');
    Route::group(['prefix' => 'setting','as' => 'setting.'], function () {
        Route::resource('database',DatabaseController::class);
        Route::resource('tool',ToolController::class);
        Route::resource('language',LanguageController::class);
        Route::resource('framework',FrameworkController::class);
        Route::resource('religion',ReligionController::class);
        Route::resource('social-media',SocialMediaController::class);
        Route::resource('work-type',WorkTypeController::class);
        Route::resource('service',ServiceController::class);
        Route::resource('library',LibraryController::class);
        Route::resource('role',RoleController::class);
        Route::resource('educational-level',EducationalLevelController::class);
    });
    Route::resource('profile',ProfileController::class);
    Route::resource('education-record',EducationRecordController::class);
    Route::resource('work-experience',WorkExperienceController::class);
    Route::resource('contact',ContactController::class);
    Route::resource('project',ProjectController::class);
});
Route::post('image/store',[ImageController::class,'store'])->name('image.store');
Route::get('/', function () {
    return view('client.home');
})->name('client.home');
Route::get('/work', function () {
    return view('client.work-show');
})->name('work.show');

resources/views/setting/database.blade.php
@extends('layouts.admin.app')

@push('css')
    <link rel="stylesheet" type="text/css" href="{{ asset('custom/css/datatables.min.css') }}"/>
    <link rel="stylesheet" href="{{ asset('custom/css/my.css') }}">
@endpush
@section('breadcrumb')
    <div class="page-header">
        <h3 class="page-title"> Database </h3>
        <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Setting</a></li>
            <li class="breadcrumb-item active" aria-current="page">Database</li>
        </ol>
        </nav>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
            <p class="card-description">
                <button type="button" class="btn btn-inverse-primary" data-toggle="modal" data-target="#modal_add"><i class="mdi mdi-plus"></i>Tambah</button>
            </p>
            <div class="template-demo">
                <x-table id="datatable">
                    @slot('head')
                        <tr>
                            <th>No.</th>
                            <th>Nama</th>
                            <th>Aksi</th>
                        </tr>
                    @endslot
                </x-table>
            </div>
            </div>
        </div>
        </div>
    </div>
@endsection

@section('modal')
    <x-modal id="modal_add" header="Form Tambah">
        <x-form action="" method="post" submit="Simpan" id="form_add">
            <x-input id="add_name" name="add_name" label="Nama" placeholder="Cth. MySQL"/>
        </x-form>
    </x-modal>
    <x-modal id="modal_edit" header="Form Edit">
        <x-form action="" method="put" submit="Update" id="form_edit">
            <x-input id="edit_name" name="edit_name" label="Nama" placeholder="Cth. MySQL"/>
        </x-form>
    </x-modal>
@endsection

@push('js')
    <script type="text/javascript" src="{{ asset('custom/js/datatables.min.js') }}"></script>
    <script>
        let index_url = "{{ route('setting.database.index') }}"
        let store_url = "{{ route('setting.database.store') }}"
        let update_url = "{{ route('setting.database.update','-id-') }}"
        let delete_url = "{{ route('setting.database.destroy','-id-') }}"
        let using_ajax_get_request = 0

        let columns = [
            { data: 'name' }
        ]
        function show_detail(data) {
            $('#edit_name').val(data.name)
        }

        let table = generate_datatable('Database',index_url,columns)
        generate_update_listener('form_edit',table)
        generate_store_listener('form_add',store_url,table)
        generate_delete_listener(delete_url,table)
        generate_show_listener(update_url,using_ajax_get_request)
    </script>
@endpush

resources/views/setting/educational-level.blade.php
@extends('layouts.admin.app')

@push('css')
    <link rel="stylesheet" type="text/css" href="{{ asset('custom/css/datatables.min.css') }}"/>
    <link rel="stylesheet" href="{{ asset('custom/css/my.css') }}">
@endpush
@section('breadcrumb')
    <div class="page-header">
        <h3 class="page-title"> Educational Level </h3>
        <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Setting</a></li>
            <li class="breadcrumb-item active" aria-current="page">Educational Level</li>
        </ol>
        </nav>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
            <p class="card-description">
                <button type="button" class="btn btn-inverse-primary" data-toggle="modal" data-target="#modal_add"><i class="mdi mdi-plus"></i>Tambah</button>
            </p>
            <div class="template-demo">
                <x-table id="datatable">
                    @slot('head')
                        <tr>
                            <th>No.</th>
                            <th>Nama</th>
                            <th>Desk</th>
                            <th>Aksi</th>
                        </tr>
                    @endslot
                </x-table>
            </div>
            </div>
        </div>
        </div>
    </div>
@endsection

@section('modal')
    <x-modal id="modal_add" header="Form Tambah">
        <x-form action="" method="post" submit="Simpan" id="form_add">
            <x-input id="add_name" name="add_name" label="Nama" placeholder="Cth. S1"/>
            <x-textarea id="add_desc" name="add_desc" label="Deskripsi" placeholder="Cth. Strata 1"/>
        </x-form>
    </x-modal>
    <x-modal id="modal_edit" header="Form Edit">
        <x-form action="" method="put" submit="Update" id="form_edit">
            <x-input id="edit_name" name="edit_name" label="Nama" placeholder="Cth. S1"/>
            <x-textarea id="edit_desc" name="edit_desc" label="Deskripsi" placeholder="Cth. Strata 1"/>
        </x-form>
    </x-modal>
@endsection

@push('js')
    <script type="text/javascript" src="{{ asset('custom/js/datatables.min.js') }}"></script>
    <script>
        let index_url = "{{ route('setting.educational-level.index') }}"
        let store_url = "{{ route('setting.educational-level.store') }}"
        let update_url = "{{ route('setting.educational-level.update','-id-') }}"
        let delete_url = "{{ route('setting.educational-level.destroy','-id-') }}"
        let using_ajax_get_request = 1

        let columns = [
            { data: 'name' },
            { data: 'desc' }
        ]
        function show_detail(data) {
            $('#edit_name').val(data.name)
            $('#edit_desc').val(data.desc)
        }

        let table = generate_datatable('Educational Level',index_url,columns)
        generate_update_listener('form_edit',table)
        generate_store_listener('form_add',store_url,table)
        generate_delete_listener(delete_url,table)
        generate_show_listener(update_url,using_ajax_get_request)
    </script>
@endpush

resources/views/setting/framework.blade.php
@extends('layouts.admin.app')

@push('css')
    <link rel="stylesheet" type="text/css" href="{{ asset('custom/css/datatables.min.css') }}"/>
    <link rel="stylesheet" href="{{ asset('custom/css/my.css') }}">
@endpush

@section('breadcrumb')
    <div class="page-header">
        <h3 class="page-title"> Framework </h3>
        <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Setting</a></li>
            <li class="breadcrumb-item active" aria-current="page">Framework</li>
        </ol>
        </nav>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
            <p class="card-description">
                <button type="button" class="btn btn-inverse-primary" data-toggle="modal" data-target="#modal_add"><i class="mdi mdi-plus"></i>Tambah</button>
            </p>
            <div class="template-demo">
                <x-table id="datatable">
                    @slot('head')
                        <tr>
                            <th>No.</th>
                            <th>Nama</th>
                            <th>Bahasa</th>
                            <th>Aksi</th>
                        </tr>
                    @endslot
                </x-table>
            </div>
            </div>
        </div>
        </div>
    </div>
@endsection

@section('modal')
    <x-modal id="modal_add" header="Form Tambah">
        <x-form action="" method="post" submit="Simpan" id="form_add">
            <x-input id="add_name" name="add_name" label="Nama" placeholder="Cth. Laravel"/>
            <x-select id="add_language" name="add_language" label="Bahasa" :options="$languages"/>
        </x-form>
    </x-modal>
    <x-modal id="modal_edit" header="Form Edit">
        <x-form action="" method="put" submit="Update" id="form_edit">
            <x-input id="edit_name" name="edit_name" label="Nama" placeholder="Cth. Laravel"/>
            <x-select id="edit_language" name="edit_language" label="Bahasa" :options="$languages"/>
        </x-form>
    </x-modal>
@endsection

@push('js')
    <script type="text/javascript" src="{{ asset('custom/js/datatables.min.js') }}"></script>
    <script>
        let index_url = "{{ route('setting.framework.index') }}"
        let store_url = "{{ route('setting.framework.store') }}"
        let update_url = "{{ route('setting.framework.update','-id-') }}"
        let delete_url = "{{ route('setting.framework.destroy','-id-') }}"
        let using_ajax_get_request = 1

        let columns = [
            { data: 'name' },
            { data: 'language.name' }
        ]
        function show_detail(data) {
            $('#edit_name').val(data.name)
            $('#edit_language').val(data.language_id)
        }

        let table = generate_datatable('Framework',index_url,columns)
        generate_update_listener('form_edit',table)
        generate_store_listener('form_add',store_url,table)
        generate_delete_listener(delete_url,table)
        generate_show_listener(update_url,using_ajax_get_request)
    </script>
@endpush

resources/views/setting/language.blade.php
@extends('layouts.admin.app')

@push('css')
    <link rel="stylesheet" type="text/css" href="{{ asset('custom/css/datatables.min.css') }}"/>
    <link rel="stylesheet" href="{{ asset('custom/css/my.css') }}">
@endpush

@section('breadcrumb')
    <div class="page-header">
        <h3 class="page-title"> Language </h3>
        <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Setting</a></li>
            <li class="breadcrumb-item active" aria-current="page">Language</li>
        </ol>
        </nav>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
            <p class="card-description">
                <button type="button" class="btn btn-inverse-primary" data-toggle="modal" data-target="#modal_add"><i class="mdi mdi-plus"></i>Tambah</button>
            </p>
            <div class="template-demo">
                <x-table id="datatable">
                    @slot('head')
                        <tr>
                            <th>No.</th>
                            <th>Nama</th>
                            <th>Aksi</th>
                        </tr>
                    @endslot
                </x-table>
            </div>
            </div>
        </div>
        </div>
    </div>
@endsection

@section('modal')
    <x-modal id="modal_add" header="Form Tambah">
        <x-form action="" method="post" submit="Simpan" id="form_add">
            <x-input id="add_name" name="add_name" label="Nama" placeholder="Cth. PHP"/>
            <x-input-icon id="add_icon" name="add_icon" placeholder="Cth. mdi mdi-instagram" label="Ikon" />
        </x-form>
    </x-modal>
    <x-modal id="modal_edit" header="Form Edit">
        <x-form action="" method="put" submit="Update" id="form_edit">
            <x-input id="edit_name" name="edit_name" label="Nama" placeholder="Cth. PHP"/>
            <x-input-icon id="edit_icon" name="edit_icon" placeholder="Cth. mdi mdi-instagram" label="Ikon" />
        </x-form>
    </x-modal>
@endsection

@push('js')
    <script type="text/javascript" src="{{ asset('custom/js/datatables.min.js') }}"></script>
    <script>
        let index_url = "{{ route('setting.language.index') }}"
        let store_url = "{{ route('setting.language.store') }}"
        let update_url = "{{ route('setting.language.update','-id-') }}"
        let delete_url = "{{ route('setting.language.destroy','-id-') }}"
        let using_ajax_get_request = 1

        let columns = [
            { data: 'name' }
        ]
        function show_detail(data) {
            $('#edit_name').val(data.name)
            $('#edit_icon').val(data.icon)
            $('#edit_icon_privew').attr('class',data.icon)
        }
        generate_icon_listener('add_icon','add_icon_privew')
        generate_icon_listener('edit_icon','edit_icon_privew')
        let table = generate_datatable('Language',index_url,columns)
        generate_update_listener('form_edit',table)
        generate_store_listener('form_add',store_url,table)
        generate_delete_listener(delete_url,table)
        generate_show_listener(update_url,using_ajax_get_request)
    </script>
@endpush

resources/views/setting/library.blade.php
@extends('layouts.admin.app')

@push('css')
    <link rel="stylesheet" type="text/css" href="{{ asset('custom/css/datatables.min.css') }}"/>
    <link rel="stylesheet" href="{{ asset('custom/css/my.css') }}">
@endpush
@section('breadcrumb')
    <div class="page-header">
        <h3 class="page-title"> Library </h3>
        <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Setting</a></li>
            <li class="breadcrumb-item active" aria-current="page">Library</li>
        </ol>
        </nav>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
            <p class="card-description">
                <button type="button" class="btn btn-inverse-primary" data-toggle="modal" data-target="#modal_add"><i class="mdi mdi-plus"></i>Tambah</button>
            </p>
            <div class="template-demo">
                <x-table id="datatable">
                    @slot('head')
                        <tr>
                            <th>No.</th>
                            <th>Nama</th>
                            <th>Desk</th>
                            <th>Aksi</th>
                        </tr>
                    @endslot
                </x-table>
            </div>
            </div>
        </div>
        </div>
    </div>
@endsection

@section('modal')
    <x-modal id="modal_add" header="Form Tambah">
        <x-form action="" method="post" submit="Simpan" id="form_add">
            <x-input id="add_name" name="add_name" label="Nama" placeholder="Cth. Laravel Excel"/>
            <x-textarea id="add_desc" name="add_desc" label="Deskripsi" placeholder="Cth. Adalah livbrary yang digunakan untuk import dan export file bertipe xlsx (excel)"/>

        </x-form>
    </x-modal>
    <x-modal id="modal_edit" header="Form Edit">
        <x-form action="" method="put" submit="Update" id="form_edit">
            <x-input id="edit_name" name="edit_name" label="Nama" placeholder="Cth. Laravel Excel"/>
            <x-textarea id="edit_desc" name="edit_desc" label="Deskripsi" placeholder="Cth. Adalah livbrary yang digunakan untuk import dan export file bertipe xlsx (excel)"/>
        </x-form>
    </x-modal>
@endsection

@push('js')
    <script type="text/javascript" src="{{ asset('custom/js/datatables.min.js') }}"></script>
    <script>
        let index_url = "{{ route('setting.library.index') }}"
        let store_url = "{{ route('setting.library.store') }}"
        let update_url = "{{ route('setting.library.update','-id-') }}"
        let delete_url = "{{ route('setting.library.destroy','-id-') }}"
        let using_ajax_get_request = 1

        let columns = [
            { data: 'name' },
            { data: 'desc' }

        ]
        function show_detail(data) {
            $('#edit_name').val(data.name)
            $('#edit_desc').val(data.desc)
        }

        let table = generate_datatable('Library',index_url,columns)
        generate_update_listener('form_edit',table)
        generate_store_listener('form_add',store_url,table)
        generate_delete_listener(delete_url,table)
        generate_show_listener(update_url,using_ajax_get_request)
    </script>
@endpush

resources/views/setting/religion.blade.php
@extends('layouts.admin.app')
@push('css')
    <link rel="stylesheet" type="text/css" href="{{ asset('custom/css/datatables.min.css') }}"/>
    <link rel="stylesheet" href="{{ asset('custom/css/my.css') }}">
@endpush
@section('breadcrumb')
    <div class="page-header">
        <h3 class="page-title"> Religion </h3>
        <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Setting</a></li>
            <li class="breadcrumb-item active" aria-current="page">Religion</li>
        </ol>
        </nav>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
            <p class="card-description">
                <button type="button" class="btn btn-inverse-primary" data-toggle="modal" data-target="#modal_add"><i class="mdi mdi-plus"></i>Tambah</button>
            </p>
            <div class="template-demo">
                <x-table id="datatable">
                    @slot('head')
                        <tr>
                            <th>No.</th>
                            <th>Nama</th>
                            <th>Aksi</th>
                        </tr>
                    @endslot
                </x-table>
            </div>
            </div>
        </div>
        </div>
    </div>
@endsection

@section('modal')
    <x-modal id="modal_add" header="Form Tambah">
        <x-form action="" method="post" submit="Simpan" id="form_add">
            <x-input id="add_name" name="add_name" label="Nama" placeholder="Cth. MySQL"/>
        </x-form>
    </x-modal>
    <x-modal id="modal_edit" header="Form Edit">
        <x-form action="" method="put" submit="Update" id="form_edit">
            <x-input id="edit_name" name="edit_name" label="Nama" placeholder="Cth. MySQL"/>
        </x-form>
    </x-modal>
@endsection

@push('js')
    <script type="text/javascript" src="{{ asset('custom/js/datatables.min.js') }}"></script>
    <script>
        let index_url = "{{ route('setting.religion.index') }}"
        let store_url = "{{ route('setting.religion.store') }}"
        let update_url = "{{ route('setting.religion.update','-id-') }}"
        let delete_url = "{{ route('setting.religion.destroy','-id-') }}"
        let using_ajax_get_request = 0

        let columns = [
            { data: 'name' }
        ]
        function show_detail(data) {
            $('#edit_name').val(data.name)
        }

        let table = generate_datatable('Religion',index_url,columns)
        generate_update_listener('form_edit',table)
        generate_store_listener('form_add',store_url,table)
        generate_delete_listener(delete_url,table)
        generate_show_listener(update_url,using_ajax_get_request)
    </script>
@endpush

resources/views/setting/role.blade.php
@extends('layouts.admin.app')

@push('css')
    <link rel="stylesheet" type="text/css" href="{{ asset('custom/css/datatables.min.css') }}"/>
    <link rel="stylesheet" href="{{ asset('custom/css/my.css') }}">
@endpush

@section('breadcrumb')
    <div class="page-header">
        <h3 class="page-title"> Role </h3>
        <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Setting</a></li>
            <li class="breadcrumb-item active" aria-current="page">Role</li>
        </ol>
        </nav>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
            <p class="card-description">
                <button type="button" class="btn btn-inverse-primary" data-toggle="modal" data-target="#modal_add"><i class="mdi mdi-plus"></i>Tambah</button>
            </p>
            <div class="template-demo">
                <x-table id="datatable">
                    @slot('head')
                        <tr>
                            <th>No.</th>
                            <th>Nama</th>
                            <th>Aksi</th>
                        </tr>
                    @endslot
                </x-table>
            </div>
            </div>
        </div>
        </div>
    </div>
@endsection

@section('modal')
    <x-modal id="modal_add" header="Form Tambah">
        <x-form action="" method="post" submit="Simpan" id="form_add">
            <x-input id="add_name" name="add_name" label="Nama" placeholder="Cth. Fullstack"/>
            <x-checkbox id="add_is_developer" name="add_is_developer" label="Pengembang"/>
            <x-textarea id="add_desc" name="add_desc" label="Deskripsi" rows="5" placeholder="Cth. Adalah pengembang perangkat lunak yang memiliki kemampuan di berbagai pokok keahlian untuk membuat produk perangkat lunak"/>
        </x-form>
    </x-modal>
    <x-modal id="modal_edit" header="Form Edit">
        <x-form action="" method="put" submit="Update" id="form_edit">
            <x-input id="edit_name" name="edit_name" label="Nama" placeholder="Cth. Fullstack"/>
            <x-checkbox id="edit_is_developer" name="edit_is_developer" label="Pengembang"/>
            <x-textarea id="edit_desc" name="edit_desc" label="Deskripsi" rows="5" placeholder="Cth. Adalah pengembang perangkat lunak yang memiliki kemampuan di berbagai pokok keahlian untuk membuat produk perangkat lunak"/>
        </x-form>
    </x-modal>
@endsection

@push('js')
    <script type="text/javascript" src="{{ asset('custom/js/datatables.min.js') }}"></script>
    <script>
        let index_url = "{{ route('setting.role.index') }}"
        let store_url = "{{ route('setting.role.store') }}"
        let update_url = "{{ route('setting.role.update','-id-') }}"
        let delete_url = "{{ route('setting.role.destroy','-id-') }}"
        let using_ajax_get_request = 1

        let columns = [
            { data: 'name' }
        ]
        function show_detail(data) {
            $('#edit_name').val(data.name)
            $("#edit_is_developer").prop("checked", data.is_developer);
            $('#edit_desc').val(data.desc)
        }

        let table = generate_datatable('Role',index_url,columns)
        generate_update_listener('form_edit',table)
        generate_store_listener('form_add',store_url,table)
        generate_delete_listener(delete_url,table)
        generate_show_listener(update_url,using_ajax_get_request)
    </script>
@endpush

resources/views/setting/service.blade.php
@extends('layouts.admin.app')

@push('css')
    <link rel="stylesheet" type="text/css" href="{{ asset('custom/css/datatables.min.css') }}"/>
    <link rel="stylesheet" href="{{ asset('custom/css/my.css') }}">
@endpush
@section('breadcrumb')
    <div class="page-header">
        <h3 class="page-title"> Service </h3>
        <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Setting</a></li>
            <li class="breadcrumb-item active" aria-current="page">Service</li>
        </ol>
        </nav>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
            <p class="card-description">
                <button type="button" class="btn btn-inverse-primary" data-toggle="modal" data-target="#modal_add"><i class="mdi mdi-plus"></i>Tambah</button>
            </p>
            <div class="template-demo">
                <x-table id="datatable">
                    @slot('head')
                        <tr>
                            <th>No.</th>
                            <th>Nama</th>
                            <th>Desk</th>
                            <th>Aksi</th>
                        </tr>
                    @endslot
                </x-table>
            </div>
            </div>
        </div>
        </div>
    </div>
@endsection

@section('modal')
    <x-modal id="modal_add" header="Form Tambah">
        <x-form action="" method="post" submit="Simpan" id="form_add">
            <x-input id="add_name" name="add_name" label="Nama" placeholder="Cth. Company Profile"/>
            <x-textarea id="add_desc" name="add_desc" label="Deskripsi" placeholder="Cth. Company Profile"/>
        </x-form>
    </x-modal>
    <x-modal id="modal_edit" header="Form Edit">
        <x-form action="" method="put" submit="Update" id="form_edit">
            <x-input id="edit_name" name="edit_name" label="Nama" placeholder="Cth. Company Profile"/>
            <x-textarea id="edit_desc" name="edit_desc" label="Deskripsi" placeholder="Cth. Company Profile"/>
        </x-form>
    </x-modal>
@endsection

@push('js')
    <script type="text/javascript" src="{{ asset('custom/js/datatables.min.js') }}"></script>
    <script>
        let index_url = "{{ route('setting.service.index') }}"
        let store_url = "{{ route('setting.service.store') }}"
        let update_url = "{{ route('setting.service.update','-id-') }}"
        let delete_url = "{{ route('setting.service.destroy','-id-') }}"
        let using_ajax_get_request = 1

        let columns = [
            { data: 'name' },
            { data: 'desc' }
        ]
        function show_detail(data) {
            $('#edit_name').val(data.name)
            $('#edit_desc').val(data.desc)
        }

        let table = generate_datatable('Service',index_url,columns)
        generate_update_listener('form_edit',table)
        generate_store_listener('form_add',store_url,table)
        generate_delete_listener(delete_url,table)
        generate_show_listener(update_url,using_ajax_get_request)
    </script>
@endpush